export const REQUEST_USER_LIST_TO_SPRING = 'REQUEST_USER_LIST_TO_SPRING'
export const REQUEST_USER_TO_SPRING = 'REQUEST_USER_TO_SPRING'

export const SET_ACCESS_TOKEN = "SET_ACCESS_TOKEN"
export const SET_USER = "SET_USER"